version: "3.1"
services:
  db:
    image: mongo
    restart: always
    networks:
      - db_network # for API reqs
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASSWORD
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
    volumes:
      - db_vol:/data/db

  db-interface:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $DB_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $DB_PASSWORD
      ME_CONFIG_SITE_BASEURL: /db_interface/
      ME_CONFIG_MONGODB_SERVER: db
    networks:
      - db_network # access db
      - web_network # access the interface
    depends_on:
      - db

  backend:
    build: ./backend
    image: pk13055/fastapi-template:mongo
    restart: always
    volumes:
      - ./backend:/app
      - static_vol:/app/app/static
      - media_vol:/app/uploads
    environment:
      PORT: 8080
      DEBUG: $DEBUG
      SECRET_KEY: $SECRET_KEY
      DATABASE_URL: $DATABASE_URL
    depends_on:
      - db
    networks:
      - db_network # for data fetching/upload
      - web_network # for web API

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx:/etc/nginx/conf.d/
      - static_vol:/app/app/static
      - media_vol:/app/uploads
    depends_on:
      - backend
      - db-interface
    networks:
      - web_network

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  static_vol:
  media_vol:
  db_vol:
